import { PrismaClient } from '@prisma/client';
import fs from 'fs';
import sharp from 'sharp';
import { createClient } from '@supabase/supabase-js';

const prisma = new PrismaClient();

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
const supabase = createClient(supabaseUrl, supabaseKey);

async function main() {
  try {
    // 1. Get the admin user
    const user = await prisma.user.findUnique({
      where: { email: 'guruprasath23062008@gmail.com' }
    });
    if (!user) throw new Error('User not found');

    console.log('1. User found:', user.email);

    // 2. Compress and upload image
    const buffer = fs.readFileSync('./public/logo.jpeg');
    const finalBuffer = await sharp(buffer).jpeg({ quality: 75 }).toBuffer();
    
    const filename = `${user.id}/test-prompt-${Date.now()}.jpg`;
    const { error } = await supabase.storage.from('prompts').upload(filename, finalBuffer, { contentType: 'image/jpeg' });
    if (error) throw error;
    
    const { data: { publicUrl } } = supabase.storage.from('prompts').getPublicUrl(filename);
    console.log('2. Image uploaded to Supabase:', publicUrl);

    // 3. Create a test prompt
    const category = await prisma.category.findFirst() || await prisma.category.create({
      data: { name: 'Test Category', slug: 'test-category', description: 'Test' }
    });

    const prompt = await prisma.prompt.create({
      data: {
        title: 'Auto-Generated Test Prompt',
        slug: `test-prompt-${Date.now()}`,
        description: 'This prompt was automatically generated by the AI to test the backend systems.',
        promptText: 'You are an advanced test AI. Analyze this data and provide insights.',
        sampleImages: JSON.stringify([publicUrl]),
        tags: 'test, ai',
        recommendedAI: 'ChatGPT',
        price: 5.00,
        sellerId: user.id,
        categoryId: category.id
      }
    });

    console.log('3. Prompt created successfully in database:', prompt.title);
    console.log('TEST COMPLETED SUCCESSFULLY!');
    
  } catch (err) {
    console.error('Test Failed:', err);
  } finally {
    await prisma.$disconnect();
  }
}
main();
